<a href="https://colab.research.google.com/github/Nivetha-B93/Data-Cleaning-Pipeline-for-SaaS-Dataset/blob/main/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment 3**
## Python DA Assignment —Numpy and Pandas

1. Create a 1D NumPy Array:

Create a 1D NumPy array named temperatures_w1 for Week 1 with the following
values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [ ]:
import numpy as np
import pandas as pd
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

# 2. Inspection and Properties:

● Inspect the shape, data type, and the number of elements in the array. Inspect
# **the shape of the temperatures_w1 array.**

In [ ]:
temperatures_w1.shape

(7,)

In [ ]:
temperatures_w1.size

7

In [ ]:
temperatures_w1.dtype

dtype('float64')

3. Array Operations:

● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
Fahrenheit = (Celsius * 9/5) + 32
● Find the maximum, minimum, and mean temperatures for the week.

In [ ]:
Fahrenheit=(temperatures_w1*9/5)+32
Fahrenheit

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [ ]:
max_temperature=max(Fahrenheit)
print(max_temperature)

78.98

In [ ]:
min_temperature=min(Fahrenheit)
print(min_temperature)

69.44

In [ ]:
mean_temperature=mean(Fahrenheit)
print(mean_temperature)

74.37714285714286

In [ ]:
maxtemperature_celcius=max(temperatures_w1)
print(maxtemperature_celcius)

26.1

In [ ]:
mintemperature_celcius=min(temperatures_w1)
print(mintemperature_celcius)

20.8

In [ ]:
from numpy._core.fromnumeric import mean
meantemperature_celcius=mean(temperatures_w1)
print(meantemperature_celcius)

23.542857142857144

4. Array Slicing and Indexing:

● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.

In [ ]:
# First three days
first_three = temperatures_w1[:3]

# Weekend (last two days)
weekend = temperatures_w1[-2:]

# Middle three days
middle_three = temperatures_w1[2:5]

print("First three days:", first_three)
print("Weekend:", weekend)
print("Middle three days:", middle_three)

First three days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

5. Create a 2D Array:

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [ ]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

6. Inspect and Slice the 2D Array:

● Inspect and print the shape, data type, and total number of elements in the
temperatures array.
● Extract the temperatures for each week and the weekends (last two days) for
both weeks.

In [ ]:
temperatures.shape

(2, 7)

In [ ]:
temperatures.dtype

In [ ]:
temperatures.size

In [ ]:
week1=temperatures[0]
week2=temperatures[1]
print("week1 temperatures are:",week1)
print("week2 temperatures are:",week2)

In [ ]:
weekend_w1=temperatures[0,5:]
weekend_w2=temperatures[1,5:]
print("weekend temperature of week1 is:",weekend_w1)
print("weekend temperature of week2 is:",weekend_w2)

1. Creating Pandas Series:
● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [ ]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

2. Indexing and Slicing:
● Use the integer index position to access the mark of the 1st rank student.

In [ ]:
print(marks.iloc[0])

Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
labels.

In [ ]:
print(marks.loc["Rank1":"Rank3"])

Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

In [ ]:
print(marks.iloc[2])

Apply a boolean mask to filter the Series and retrieve the ranks where the marks are
greater than 90.

In [ ]:
results=marks[marks>90]
print(results)

3. Manipulating Series:
● Modify the mark of the student with the 1st rank to 100.

In [ ]:
marks.iloc[0]=100
marks

Remove the entry corresponding to the last rank from the Series.

In [ ]:
marks = marks.drop('Rank5')

print(marks)

Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
cgpa = marks / 10

print(cgpa)

1. Creating Pandas DataFrame:

● Create a Pandas DataFrame named transactions with the following data: ➢
TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',

'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [ ]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Data Exploration:
● Display the transactions DataFrame and its basic information, including head, tail,
shape, column names, and data types.

In [ ]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [ ]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [ ]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [ ]:
transactions.shape

(9, 4)

In [ ]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [ ]:
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

● Display only the 'ProductCategory' and 'Amount' columns.

In [ ]:
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

● Retrieve the last 3 columns of the DataFrame using iloc or loc.

In [ ]:
transactions.iloc[:,-3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [ ]:
transactions[(transactions['Region']=='North')&(transactions['Amount']>200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

Find the value counts for the 'ProductCategory' column.

In [ ]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

Find the unique values in the 'Region' column.

In [ ]:
transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

Group by 'Region' and find the mean amount for each region.

In [ ]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [ ]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

● Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [ ]:
transactions['Discount']=transactions['Amount']*0.1
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

● Remove the row with TransactionID 109.

In [ ]:
transactions.drop(
    transactions[transactions['TransactionID'] == 109].index,
    inplace=True
)

Delete the 'Discount' column from the DataFrame.

In [ ]:
transactions.drop('Discount', axis=1, inplace=True)

In [ ]:
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400